---
roadmap:
  name: Roadmap Epigenomics Project
  url: https://personal.broadinstitute.org/jernst/MODEL_IMPUTED12MARKS
gencode:
  name: GENCODE v44
  url: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_44/gencode.v44.annotation.gtf.gz
uniprot:
  name: UniProtKB/Swiss-Prot
  url: https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/taxonomic_divisions/uniprot_sprot_human.dat.gz
reactome:
  name: Reactome
  url:
    - https://reactome.org/download/current/ReactomePathways.txt
    - https://reactome.org/download/current/ReactomePathwaysRelation.txt
    - https://reactome.org/download/current/Ensembl2Reactome_All_Levels.txt
    - https://reactome.org/download/current/ReactionPMIDS.txt
gaf:
  name: GO Annotation File (GAF)
  url: http://geneontology.org/gene-associations/goa_human.gaf.gz
coxpressdb:
  name: Coxpress DB
  url: https://zenodo.org/record/6861444/files/Hsa-u.v22-05.G16651-S245698.combat_pca.subagging.z.d.zip
tflink:
  name: TFLink
  url: https://cdn.netbiol.org/tflink/download_files/TFLink_Homo_sapiens_interactions_All_simpleFormat_v1.0.tsv.gz
string:
  name: STRING PPI
  url: https://stringdb-downloads.org/download/protein.links.v12.0/9606.protein.links.v12.0.txt.gz
tadmap:
  name: TADMap
  url: https://cb.csail.mit.edu/cb/tadmap/TADMap_geneset_hs.csv
gtex_eqtl:
  name: GTEx eQTL
  bucket: adult-gtex
  path: bulk-qtl/v8/single-tissue-cis-qtl/GTEx_Analysis_v8_eQTL.tar
topld:
  name: TopLD
  url:
    AFR: http://topld.genetics.unc.edu/downloads/downloads/AFR/SNV/AFR_xx_no_filter_0.2_1000000_LD.csv.gz
    EAS: http://topld.genetics.unc.edu/downloads/downloads/EAS/SNV/EAS_xx_no_filter_0.2_1000000_LD.csv.gz
    EUR: http://topld.genetics.unc.edu/downloads/downloads/EUR/SNV/EUR_xx_no_filter_0.2_1000000_LD.csv.gz
    SAS: http://topld.genetics.unc.edu/downloads/downloads/SAS/SNV/SAS_xx_no_filter_0.2_1000000_LD.csv.gz
hocomoco:
  name: HOCOMOCOv11
  url:
    annotation: https://hocomoco11.autosome.org/final_bundle/hocomoco11/core/HUMAN/mono/HOCOMOCOv11_core_annotation_HUMAN_mono.tsv
    pwm: https://hocomoco11.autosome.org/final_bundle/hocomoco11/core/HUMAN/mono/HOCOMOCOv11_core_pwm_HUMAN_mono.tar.gz
favor:
  name: FAVOR
  url:
    chr16: https://dataverse.harvard.edu/api/access/datafile/6388551
cadd:
  name: Combined Annotation Dependent Depletion (CADD)
  url: https://forgedb.cancer.gov/api/cadd/v1.0/cadd.forgedb.csv.gz
refseq:
  name: RefSeq Closest Gene
  url: https://forgedb.cancer.gov/api/closest_gene/v1.0/closest_gene.forgedb.csv.gz
tfbs:
  name: UCSC TFBS Clusters
  url: https://hgdownload.soe.ucsc.edu/goldenpath/hg38/database/encRegTfbsClustered.txt.gz
dbsuper:
  name: dbSUPER
  url: http://asntech.org/dbsuper/data/dbSUPER_v1_GRCh38.bed.gz
abc:
  name: Activity-By-Contact (ABC)
  url: https://forgedb.cancer.gov/api/abc/v1.0/abc.forgedb.csv.gz
roadmap_dhs:
  name: RoadMap DHS
  url: https://forgedb.cancer.gov/api/roadmap/dhs/forge2.erc2-DHS.forgedb.csv.gz
roadmap_state:
  name: Roadmap Epigenomics State
  url: https://personal.broadinstitute.org/jernst/MODEL_IMPUTED12MARKS/state_calls
roadmap_h3marks:
  name: Roadmap Epigenomics H3 Marks
  url: https://personal.broadinstitute.org/jernst/MODEL_IMPUTED12MARKS/marks
bgee:
  name: Bgee Expression Data
  url: https://bgee.org/ftp/current/download/calls/expr_calls/Homo_sapiens_expr_simple_development.tsv.gz
rna_central:
  name: RNA Central
  url:
    bed: https://ftp.ebi.ac.uk/pub/databases/RNAcentral/current_release/genome_coordinates/human.GRCh38.bed.gz
    rfam: https://ftp.ebi.ac.uk/pub/databases/RNAcentral/current_release/rfam/rfam_annotations.tsv.gz
dgv:
  name: Database of Genomic Variants
  url: http://dgv.tcag.ca/dgv/docs/GRCh38_hg38_variants_2020-02-25.txt
epd:
  name: Eukaryotic Promoter Database
  url: https://epd.epfl.ch/EPD/get_promoter_seq?db=hg38&format=bed&nb_seq=0
dbvar:
  name: NCBI dbVar
  url: https://ftp.ncbi.nlm.nih.gov/pub/dbVar/data/Homo_sapiens/by_assembly/GRCh38/vcf/GRCh38.variant_call.all.vcf.gz
dbsnp:
  name: dbSNP
  url: https://ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh38p7/VCF/00-All.vcf.gz
polyphen2:
  name: PolyPhen-2
  url: http://genetics.bwh.harvard.edu/pph2/data/polyphen-2.2.2-whess-2011_12.tab.gz
gwas:
  name: GWAS Catalog
  url: https://ftp.ebi.ac.uk/pub/databases/gwas/releases/2024/07/29/gwas-catalog-associations_ontology-annotated.tsv
enhancer_atlas:
  name: EnhancerAtlas
  url: http://www.enhanceratlas.org/data/download/enhancer_atlas_2.0/9606_all_tissues.bed
fabian:
  name: Fabian
  url: https://fabian.bioinf.mpi-inf.mpg.de/downloads/human_grch38.tar.gz
brenda_tissue_ontology:
  name: BRENDA Tissue Ontology
  url: http://purl.obolibrary.org/obo/bto.owl
